# Generated by Django 4.2.2 on 2023-09-08 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_alter_hero_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='email',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
